extends: default

rules:
  line-length:
    max: 200
    level: warning
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "on", "off"]
    check-keys: false
  comments-indentation: disable
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1
